---
#
# Project:: Vagrant Boxes
#
# Copyright 2020, Route 1337, LLC, All Rights Reserved.
#
# Maintainers:
# - Matthew Ahrenstein: matthew@route1337.com
#
# See LICENSE
#

- name: Install NginX
  apt:
    name: nginx
    state: present

- name: Remove the default NginX site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Deploy the Jenkins proxy config
  copy:
    src: jenkins.conf
    dest: /etc/nginx/sites-enabled/jenkins.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart nginx
