---
#
# Project:: Vagrant Boxes
#
# Copyright 2019, Route 1337, LLC, All Rights Reserved.
#
# Maintainers:
# - Matthew Ahrenstein: matthew@route1337.com
#
# See LICENSE
#

- name: ubuntu restart ssh
  service: name=ssh state=restarted

- name: centos restart ssh
  service: name=sshd state=restarted