---
# Configure a Docker Registry host

- name: Install Docker prerequisites
  include: prereqs.yml
  when: ansible_distribution == 'Ubuntu'

- name: Install Docker Registry
  include: registry.yml
  when: ansible_distribution == 'Ubuntu'