---
#
# Project:: Vagrant Boxes
#
# Copyright 2020, Route 1337, LLC, All Rights Reserved.
#
# Maintainers:
# - Matthew Ahrenstein: matthew@route1337.com
#
# See LICENSE
#

# Configure a Docker Registry host

- name: Install Docker prerequisites
  import_tasks: prereqs.yml
  when: ansible_distribution == 'Ubuntu'

- name: Install Docker Registry
  import_tasks: registry.yml
  when: ansible_distribution == 'Ubuntu'
