# -*- mode: ruby -*-
# vi: set ft=ruby :
#
# Project:: Vagrant Boxes
#
# Copyright 2019, Route 1337, LLC, All Rights Reserved.
#
# Maintainers:
# - Matthew Ahrenstein: matthew@route1337.com
#
# See LICENSE
#

Vagrant.configure("2") do |config|

  config.vm.define :javadev do |javadev|

    javadev.vm.box = "ubuntu/bionic64"
    javadev.vm.hostname = "javadev.vg.route1337.com"
    javadev.vm.synced_folder "~/Scratch/", "/scratch"
    javadev.vm.synced_folder "~/Downloads/", "/downloads"

    # virtualbox VM parameters (RAM, CPU etc)
    javadev.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end

    # Private networking - so machines can speak to each other:
    javadev.vm.network :private_network, ip: "192.168.33.30"

    # Provision with Ansible
    javadev.vm.provision :ansible do |ansible|
      ansible.inventory_path = "../../ansible/vagrant.inv"
      ansible.playbook = "../../ansible/main.yml"
    end
  end
end
