# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define :jenkins do |jenkins|

    jenkins.vm.box = "ubuntu/trusty64"
    jenkins.vm.hostname = "jenkins.vg.route1337.com"

    # virtualbox VM parameters (RAM, CPU etc)
    jenkins.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end

    # Private networking - so machines can speak to each other:
    jenkins.vm.network :private_network, ip: "192.168.33.34"

    # Provision with Ansible
    jenkins.vm.provision :ansible do |ansible|
      ansible.inventory_path = "../../ansible/vagrant.inv"
      ansible.playbook = "../../ansible/main.yml"
    end
  end
end
