---
#
# Project:: Vagrant Boxes
#
# Copyright 2019, Route 1337, LLC, All Rights Reserved.
#
# Maintainers:
# - Matthew Ahrenstein: matthew@route1337.com
#
# See LICENSE
#

- name: Configure SSH for Vagrant
  import_tasks: sshconfig.yml
- name: Manage the root user for Vagrant
  import_tasks: rootuser.yml

