---
#
# Project:: Vagrant Boxes
#
# Copyright 2020, Route 1337, LLC, All Rights Reserved.
#
# Maintainers:
# - Matthew Ahrenstein: matthew@route1337.com
#
# See LICENSE
#

# Handlers used for various tasks in docker-host

- name: restart docker
  service:
    name: docker
    state: restarted

- name: authenticate to registry
  command: /usr/bin/docker login -u route -p onethreethreeseven dockerreg.vg.route1337.com