---
#
# Project:: Vagrant Boxes
#
# Copyright 2019, Route 1337, LLC, All Rights Reserved.
#
# Maintainers:
# - Matthew Ahrenstein: matthew@route1337.com
#
# See LICENSE
#

# Set up the basic requirements and settings of all CentOS servers

- import_tasks: prereqs.yml
  when: ansible_distribution == 'CentOS'
- import_tasks: thefuck.yml
  when: ansible_distribution == 'CentOS'
- import_tasks: bash.yml
  when: ansible_distribution == 'CentOS'
- import_tasks: rootuser.yml
  when: ansible_distribution == 'CentOS'