---
# Manage packages that should be added or removed

- name: Add the usual packages
  yum: name={{ item }} state=latest
  with_items:
    - bmon
    - vim
    - curl
    - gnupg2
    - atop
    - git
    - lsof
    - telnet

- name: Configure timezone to EST
  file:
    src: /usr/share/zoneinfo/America/New_York
    dest: /etc/localtime
    state: link
    force: yes
  notify:
    - centos reconfigure timezone

- name: Make sure the /opt directory exists
  file:
    path: /opt
    state: directory
    owner: root
    group: root
    mode: 0755

