# -*- mode: ruby -*-
# vi: set ft=ruby :
#
# Project:: Vagrant Boxes
#
# Copyright 2020, Route 1337, LLC, All Rights Reserved.
#
# Maintainers:
# - Matthew Ahrenstein: matthew@route1337.com
#
# See LICENSE
#

Vagrant.configure(2) do |config|

  config.vm.define :dedrm do |dedrm|

    dedrm.vm.box = "dedrm"
    dedrm.vm.box_url = "http://vg.route1337.com/dedrm.json"
    dedrm.vm.hostname = "dedrm.vg.route1337.com"
    dedrm.vm.synced_folder "~/Downloads/", "/hostpc"
    dedrm.vm.guest = :windows
    dedrm.vm.communicator = "winrm"
    dedrm.winrm.username = "vagrant"
    dedrm.vm.hostname = "dedrm"
    dedrm.winrm.timeout = 600
    dedrm.vm.boot_timeout = 600

    # virtualbox VM parameters (RAM, CPU etc)
    dedrm.vm.provider "virtualbox" do |vb|
      # Don't boot with headless mode
      vb.gui = true
      vb.name = "dedrm-box"
      vb.cpus = 2
      vb.memory = 2048
    end

    # Private networking - so machines can speak to each other:
    dedrm.vm.network :private_network, ip: "192.168.33.50"

    # No Ansible Provisioning
  end
end
