---
# Configure the root account

- name: Configure root SSH keys
  authorized_key:
    user: root
    key: "{{ item }}"
    state: present
    exclusive: yes
  with_items:
  - "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key"
  - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDaFqiSpsi5mkLcgNr5Rb+818XaxprjMPbB2MsouX+Vfad35Hn3sfgF0f16a+djocYPoQkclpXr5xHuNpAWJkTuRbXJdh2NqRl1rOt+9JbrBkLQtARLgjaU1+FFxp0h+zWBfefNuQLmuvPXKUJ1F5/VazhBsyopkoaQ6gv6KKW0iISeD5mDNahHIsFBDj0NIhcxyAaRHgCyOcbyrBBc1iN5WC05M8jNoCefdm4yLkvAFfbmnF8B+hM7nEfR71nGsk540WEfvetlVKKai+ZSa1GpjWXN9PEn1USCCNB7vr82oBLWCzXiGzQTTW9KXvhge4I4Nw+kqTVnveISz2oImutsYg7AIWgaz9Q3zf38bOXJ30YdF/BlPgy8QAOQWIcW9z9dJx0Il1348vtiYYg1WsWBOANFTdjWLDmrC5gMPgz13K5hK//kbrD3cLsN1x8jYlT4VjR1iV6YCn1162XnI2HWy82x1XwIIBJ7/Yi7xK1mDwuMyH963FjqP9IU1VVAhi9oyNsCeDrJ2SbSJrTPUP8BdQltR4tO5tctCf9/UIKiLb0thXQ4Hp7ZBPuzk90R4M2BicC7OJ38XXMeIO786qmbqOg/70kjA5BJmJDTLS/jbKxKScPy7ZZYl0z80+0whjiipaVWBVvQE3txCtgD5007smdY8wb16rlUnY9feODP5Q== Matthew Ahrenstein"

- name: Configure root password as "vagrant"
  user: name=root password=$5$jku/VqFgw1C9j$e1BTUBiZx.bXEukPqzkBPD1tc3xC8kJ1xFqqwffdxs9 update_password=always
