---
#
# Project:: Vagrant Boxes
#
# Copyright 2020, Route 1337, LLC, All Rights Reserved.
#
# Maintainers:
# - Matthew Ahrenstein: matthew@route1337.com
#
# See LICENSE
#

# Handlers necessary for jenkins server configuration

- name: refresh apt
  apt:
    update_cache: yes

- name: restart nginx
  service:
    name: nginx
    state: restarted