# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define :boxybrown do |boxybrown|

    boxybrown.vm.box = "ubuntu/bionic64"
    boxybrown.vm.hostname = "boxybrown.vg.route1337.com"
    boxybrown.vm.synced_folder "/Scratch/", "/scratch"
    boxybrown.vm.synced_folder "~/Downloads/", "/downloads"

    # virtualbox VM parameters (RAM, CPU etc)
    boxybrown.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end

    # Private networking - so machines can speak to each other:
    boxybrown.vm.network :private_network, ip: "192.168.33.30"

    # Provision with Ansible
    boxybrown.vm.provision :ansible do |ansible|
      ansible.inventory_path = "../../ansible/vagrant.inv"
      ansible.playbook = "../../ansible/main.yml"
    end
  end
end
