# -*- mode: ruby -*-
# vi: set ft=ruby :
#
# Project:: Vagrant Boxes
#
# Copyright 2019, Route 1337, LLC, All Rights Reserved.
#
# Maintainers:
# - Matthew Ahrenstein: matthew@route1337.com
#
# See LICENSE
#

Vagrant.configure("2") do |config|

  config.vm.define :ie6 do |ie6|

    ie6.vm.box = "ie6"
    ie6.vm.hostname = "ie6.vg.route1337.com"
    ie6.vm.box_url = "http://aka.ms/vagrant-xp-ie6"
    ie6.vm.guest = :windows
    ie6.vm.communicator = "winrm"
    ie6.winrm.username = "vagrant"
    ie6.vm.hostname = "ie6"
    ie6.winrm.timeout = 30
    ie6.vm.boot_timeout = 30

    # virtualbox VM parameters (RAM, CPU etc)
    ie6.vm.provider "virtualbox" do |vb|
      vb.gui = true
      vb.memory = 1024
      vb.cpus = 1
    end

    # There is no WinRM in XP so we can't configure private networking

    # No Ansible Provisioning
  end
end