---
#
# Project:: Vagrant Boxes
#
# Copyright 2020, Route 1337, LLC, All Rights Reserved.
#
# Maintainers:
# - Matthew Ahrenstein: matthew@route1337.com
#
# See LICENSE
#

# Configure the actual Docker container host

- name: Make sure the certs directory for the INSECURE cert exists
  file:
    path: /etc/docker/certs.d/dockerreg.vg.route1337.com
    state: directory
    mode: 0755
    owner: root
    group: root
    recurse: yes

- name: Configure Docker to allow INSECURE certs from the registry
  copy:
    src: cert.template
    dest: /etc/docker/certs.d/dockerreg.vg.route1337.com/dockerreg.vg.route1337.com.crt
    mode: 0644
    owner: root
    group: root
    force: yes
  notify:
    - restart docker
    - authenticate to registry
