---
#
# Project:: Vagrant Boxes
#
# Copyright 2020, Route 1337, LLC, All Rights Reserved.
#
# Maintainers:
# - Matthew Ahrenstein: matthew@route1337.com
#
# See LICENSE
#

# Configure the prerequisites for a Docker container host

- name: Add the Docker repository GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Add the Docker repository
  apt_repository:
    repo: 'deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable'
    state: present

- name: Refresh apt cache
  apt:
    update-cache: yes

- name: Install Docker itself
  apt:
    name: docker-ce
    state: present

- name: Install the prerequisites for Docker container management
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - python-dev
      - python-setuptools
      - python-pip
      - openssl
      - linux-image-extra-virtual # https://github.com/docker/docker/issues/15825

- name: Install required python packages
  pip:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - docker-py
      - six
      - setuptools
      - passlib
