---
#
# Project:: Vagrant Boxes
#
# Copyright 2020, Route 1337, LLC, All Rights Reserved.
#
# Maintainers:
# - Matthew Ahrenstein: matthew@route1337.com
#
# See LICENSE
#

- name: Call prerequisites
  include: prereqs.yml
- name: Install Tomcat 8.6
  include: tomcat85.yml
