---
#
# Project:: Vagrant Boxes
#
# Copyright 2020, Route 1337, LLC, All Rights Reserved.
#
# Maintainers:
# - Matthew Ahrenstein: matthew@route1337.com
#
# See LICENSE
#

- name: Add the git-lfs repository
  apt_repository:
    repo: ppa:git-core/ppa
    state: present

- name: Update APT package cache
  apt:
    update_cache: yes

- name: Install OpenJDK Java development
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - openjdk-8-jdk
      - openjdk-8-jdk-headless
      - openjdk-8-jre-headless

- name: Install Maven
  apt:
    name: maven
    state: present

- name: Install git-lfs
  apt:
    name: git-lfs
    state: present

