# -*- mode: ruby -*-
# vi: set ft=ruby :
#
# Project:: Vagrant Boxes
#
# Copyright 2019, Route 1337, LLC, All Rights Reserved.
#
# Maintainers:
# - Matthew Ahrenstein: matthew@route1337.com
#
# See LICENSE
#

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'vmware_fusion'

Vagrant.configure("2") do |config|


  config.vm.define :yosemite do |yosemite|

    yosemite.vm.box = "fusion-yosemite"
    yosemite.vm.box_url = "http://vg.route1337.com/fusion-yosemite.json"
    yosemite.vm.hostname = "yosemite.vg.route1337.com"
    yosemite.vm.synced_folder "/Scratch/", "/Scratch"

    # VMware VM parameters (RAM, CPU etc)
    ["vmware_fusion", "vmware_workstation"].each do |vmware|
      yosemite.vm.provider vmware do |v, override|
        v.vmx["memsize"] = "3072"
        v.vmx["numvcpus"] = "2"
        v.vmx["ethernet0.present"] = "TRUE"
        v.vmx["ethernet0.connectionType"] = "nat"
        v.vmx["ethernet0.virtualDev"] = "e1000e"
        v.vmx["ethernet0.wakeOnPcktRcv"] = "FALSE"
        v.vmx["ethernet0.addressType"] = "generated"
        v.gui = true
      end
    end

    # Private networking - so machines can speak to each other:
    yosemite.vm.network :private_network, ip: "192.168.40.31"

    ## Provision with Ansible
    #yosemite.vm.provision :ansible do |ansible|
    #  ansible.inventory_path = "../../ansible/vagrant.inv"
    #  ansible.playbook = "../../ansible/main.yml"
    #end
  end
end
