---
#
# Project:: Vagrant Boxes
#
# Copyright 2019, Route 1337, LLC, All Rights Reserved.
#
# Maintainers:
# - Matthew Ahrenstein: matthew@route1337.com
#
# See LICENSE
#

tomcat_java_home: "/usr/lib/jvm/java-8-oracle/jre"
tomcat_archive_name: "apache-tomcat-8.5.32"
tomcat_archive_name_ext: ".tar.gz"
tomcat_archive_url: "https://archive.apache.org/dist/tomcat/tomcat-8/v8.5.32/bin"
tomcat_home_path: "/opt/tomcat"
tomcat_archive_install_path: "{{tomcat_home_path}}/{{tomcat_archive_name}}"
tomcat_install_link: "{{tomcat_home_path}}/current"
tomcat_roles:
- manager-gui
- manager-script
- manager-jmx
- manager-status
tomcat_users: []
